[package]
name = "PLC_Bridge_Rust"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ws="0.9.1"
chrono="0.4.19"
